[phases.setup]
nixPkgs = ["ffmpeg", "python39", "python39Packages.pip", "python39Packages.setuptools"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c \"import whisper; whisper.load_model('base')\""]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT" 